#!/usr/bin/env bash
# Heavy inspiration from rxfetch

get_de_wm() {
	wm="${XDG_CURRENT_DESKTOP#*:}"
	[ "$wm" ] || wm="$DESKTOP_SESSION"

	# for most WMs
	[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
		id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>/dev/null)
		id=${id##* }
		wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t 2>/dev/null | grep '^_NET_WM_NAME' | cut -d\" -f 2)
	}

	# for non-EWMH WMs
	[ ! "$wm" ] || [ "$wm" = "LG3D" ] &&
		wm=$(pgrep -m 1 -o \
			-e "sway" \
			-e "kiwmi" \
			-e "wayfire" \
			-e "sowm" \
			-e "catwm" \
			-e "fvwm" \
			-e "dwm" \
			-e "2bwm" \
			-e "monsterwm" \
			-e "tinywm" \
			-e "xmonad")

	echo "${wm:-unknown}"
}

echo "                 ."`".            "
echo "             .-./ _=_ \.-.        "
echo "            {  (,(oYo),) }}       kern  $(uname -r) "
echo "            {{ |   "   |} }       "
echo "            { { \(---)/  }}       de/wm  $(get_de_wm) "
echo "            {{  }'-=-'{ } }       "
echo "            { { }._:_.{  }}       shell  $(echo ${SHELL}) "
echo "            {{  } -:- { } }       "
echo "            {_{ }`===`{  _}       uptime $(uptime -p | sed 's/up//') "
echo "           ((((\)     (/))))      "

